# Generated by Django 4.2.4 on 2023-10-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gobdetail',
            name='name',
        ),
    ]
