# Generated by Django 4.2.4 on 2023-10-13 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_move_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_movie', to='tickets.movie'),
        ),
    ]
